export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';
export const GET_ERRORS = "GET_ERRORS"
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT"
export const DELETE_ERRORS = "DELETE_ERRORS"
export const USERS_ERROR = 'USERS_ERROR'